openapi: 3.0.0
info:
  title: 10-E-Commerce
  version: 1.0.0
servers:
  - url: https://e-commerce-api-m52i.onrender.com/api/v1
tags:
  - name: Auth
  - name: Users
  - name: Product
  - name: Review
  - name: Order
paths:
  /auth/logout:
    get:
      tags:
        - Auth
      summary: Logout User
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: susan
                email: susan@gmail.com
                password: secret
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: ilija@gmail.com
                password: secret
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /users:
    get:
      tags:
        - Users
      summary: Get All Users
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /users/{id}:
    get:
      tags:
        - Users
      summary: Get Single User
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the user to retrieve
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /users/showMe:
    get:
      tags:
        - Users
      summary: Show Current User
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /users/updateUser:
    patch:
      tags:
        - Users
      summary: Update User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: george
                email: george@gmail.com
                password: secret
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /users/updateUserPassword:
    patch:
      tags:
        - Users
      summary: Update User Password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                currentPassword: 1secret
                newPassword: secret
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /products:
    get:
      tags:
        - Product
      summary: Get All Products
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Product
      summary: Create Product
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: accent chair 2.0
                price: 30999
                image: >-
                  https://dl.airtable.com/.attachmentThumbnails/e8bc3791196535af65f40e36993b9e1f/438bd160
                colors:
                  - "#ff0000"
                  - "#00ff00"
                  - "#0000ff"
                company: marcos
                description: >-
                  Cloud bread VHS hell of banjo bicycle rights jianbing umami
                  mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr
                  dreamcatcher waistcoat, authentic chillwave trust fund. Viral
                  typewriter fingerstache pinterest pork belly narwhal. Schlitz
                  venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki
                  trust fund hashtag kinfolk microdosing gochujang live-edge
                category: office
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /products/{id}:
    get:
      tags:
        - Product
      summary: Get Single Product
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the product to retrieve
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - Product
      summary: Update Product
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the product to update
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                price: "10001"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Product
      summary: Delete Product
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the product to delete
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /products/uploadImage:
    post:
      tags:
        - Product
      summary: Upload Image
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /products/{id}/reviews:
    get:
      tags:
        - Product
      summary: Get Single Product Reviews
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the product to retrieve reviews for
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /reviews:
    get:
      tags:
        - Review
      summary: Get All Reviews
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Review
      summary: Create Review
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                product: 67029d8e3ddc42464a1b2b8c
                rating: 1
                title: bad product!
                comment: very very bad product
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /reviews/{id}:
    get:
      tags:
        - Review
      summary: Get Single Review
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the review to retrieve
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - Review
      summary: Update Review
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the review to update
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                comment: Very good product!
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Review
      summary: Delete Review
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the review to delete
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /orders:
    post:
      tags:
        - Order
      summary: Create Order
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                tax: 499
                shippingFee: 799
                items:
                  - product: 67029cf72f5b6a66517bab08
                    amount: 3
                  - product: 67029d8e3ddc42464a1b2b8c
                    amount: 2
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Order
      summary: Get All Orders
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /orders/{id}:
    get:
      tags:
        - Order
      summary: Get Single Order
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the order to retrieve
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Order
      summary: Delete Order
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the order to delete
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
